openapi: "3.0.0"
info:
  title: "Pokemon API"
  version: "1.0.0"
paths:
  /api/pokemon/{id}:
    get:
      summary: "Get a Pokemon"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Successful response"
      operationId: pokemon_api.get_pokemon
