openapi: "3.0.0"
info:
  title: "Pokemon API"
  version: "1.0.0"
paths:
  /api/pokemon/{id}:
    get:
      summary: "Get a Pokemon"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "A Pokemon"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
